{"name": "User can search for a product -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"twotabsearchtextbox\"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nelement.find/</<@chrome://remote/content/marionette/element.js:305:16\n\n", "trace": "  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\amazon_main_page_steps.py\", line 21, in search_product\n    context.app.main_page.search_product(product)\n  File \"C:\\Users\\12405\\python-selenium-automation\\pages\\main_page.py\", line 13, in search_product\n    self.input_text(product, *self.SEARCH_INPUT)\n  File \"C:\\Users\\12405\\python-selenium-automation\\pages\\base_page.py\", line 27, in input_text\n    e = self.driver.find_element(*locator)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Open amazon page", "status": "passed", "start": 1716077466057, "stop": 1716077469308}, {"name": "When Search for mug", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"twotabsearchtextbox\"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nelement.find/</<@chrome://remote/content/marionette/element.js:305:16\n\n", "trace": "  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\amazon_main_page_steps.py\", line 21, in search_product\n    context.app.main_page.search_product(product)\n  File \"C:\\Users\\12405\\python-selenium-automation\\pages\\main_page.py\", line 13, in search_product\n    self.input_text(product, *self.SEARCH_INPUT)\n  File \"C:\\Users\\12405\\python-selenium-automation\\pages\\base_page.py\", line 27, in input_text\n    e = self.driver.find_element(*locator)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\12405\\python-selenium-automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1716077469319, "stop": 1716077474375}, {"name": "Then Search results for \"mug\" are shown", "status": "skipped", "start": 1716077475072, "stop": 1716077475072}], "parameters": [{"name": "product", "value": "mug"}, {"name": "search_result", "value": "\"mug\""}], "start": 1716077444857, "stop": 1716077475072, "uuid": "59edcc2e-d9d9-48b4-9cb2-29993eb9477d", "historyId": "15db23ee3756bd32054f3385949df41f", "fullName": "Tests for amazon search: User can search for a product", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Tests for amazon search"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}